// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1pe_cFIGxhmdrB1jQXSTaO0JWbMpT2DA',
    appId: '1:283036559044:web:78cd73c50ceef30a4a4b91',
    messagingSenderId: '283036559044',
    projectId: 'food-56b7a',
    authDomain: 'food-56b7a.firebaseapp.com',
    storageBucket: 'food-56b7a.firebasestorage.app',
    measurementId: 'G-TV01X15F1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl3xz8jkDrVuprQLs8xRfhOWoGTmEB8fE',
    appId: '1:283036559044:android:2287167e59b134a34a4b91',
    messagingSenderId: '283036559044',
    projectId: 'food-56b7a',
    storageBucket: 'food-56b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVMJU38jvQX1bw1o7wdZ72gsS8LJ6P3DA',
    appId: '1:283036559044:ios:de6959ace1ade4d94a4b91',
    messagingSenderId: '283036559044',
    projectId: 'food-56b7a',
    storageBucket: 'food-56b7a.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVMJU38jvQX1bw1o7wdZ72gsS8LJ6P3DA',
    appId: '1:283036559044:ios:de6959ace1ade4d94a4b91',
    messagingSenderId: '283036559044',
    projectId: 'food-56b7a',
    storageBucket: 'food-56b7a.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );
}
